version: '3'

services:
  playwright:
    build: ./docker/playwright
    container_name: playwright
    tty: true
    ports:
      - "9323:9323"
      - "8010:8010"
    volumes:
      - ./mount:/app
      - /app/node_modules
    environment:
      - DISPLAY=:10